---
name: Benchmark CLI

on: repository_dispatch

jobs:
  benchmark:
    name: Benchmark CLI

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Inspect Env
        run: printenv
