---
name: Benchmark CLI

on: repository_dispatch

jobs:
  benchmark:
    name: Benchmark CLI

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Inspect Env
        run: printenv

      # Checkout `this` repository
      - name: checkout/mikemimik/test-benchmark
        uses: actions/checkout@v2
        with:
          path: ${{ env.RUNNER_WORKSPACE }}

      # Checkout repository from incoming dispatch request
      - name: checkout/${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.commit_sha }}
          token: ${{ secrets.DEPLOY_PAT }}
          path: ${{ env.RUNNER_WORKSPACE }}
          fetch-depth: 1

      - name: Testing
        env:
          WORKING_DIR: ${{ env.RUNNER_WORKSPACE }}
          BENCHMARK_DIR: "test-benchmark"
          CHECKOUT_DIR: ${{ github.event.client_payload.repo }}
        run: |
          # Testing Information
          printenv
          cd "${RUNNER_WORKSPACE}"
          ls -al

      - name: Dispatched Event
        env:
          TEST_GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "event info"
